
import Head from "next/head";
import About from "./about";
import Navbar from "../components/Navbar";


export default function Home() {
    return ( 
        <div>

        <Head>
            <title>This is a Next js App</title>
            <meta name="description"  content="Generated by create next app"/>
            {/* <link rel="stylesheet" href="../styles/global.css" /> */}
        </Head>
        
        <Navbar />
        <About />

        </div>
     );
}
